### ISSUE TITLE
Ability to have icon for toggling the backdrop in actions instead of only as leading

### ISSUE THREAD

**Issue by blendstrup** [mdazharuddin1011999/flutter_backdrop#1]
Hey there,

I really like your package, the fact that it is so simple to toggle the backdrop from anywhere is amazing.

Your package also makes it really easy to implement an animated icon for toggling the backdrop, but it's only possible to implement it as a leading icon whereas I'd like to implement that icon in the actions of the appbar, so that the app is better suited for right handed people.

Is this something you could make possible?

**Comment by azhar1038** [comment]
Sorry but to make it simple, I had to hard code a few things which included fixing toggler to the left. If you want you can change it by changing appbarMenuButton() in flutter_backdrop.dart for now.

Though I will try to include that feature too later.
