### ISSUE TITLE
Using with a Sliver AppBar..

### ISSUE THREAD

**Issue by Skquark** [mdazharuddin1011999/flutter_backdrop#2]
I was very excited about using this as my solution, and was getting my project prepped for implementation, but then I realized that the Backdrop widget replaces the AppBar completely... My main ui is Sliver based with everything inside of a NestedScrollView and the title being a SliverAppBar.  Is there any possible way of adapting this for use still, or should I give up and find another way to get the effect I was looking for?  Thanks, much appreciated..

**Comment by azhar1038** [comment]
It is not possible to do with the current version. If you want you can fork it and understand how it works and implement it by yourself in your sliverappbar.
