### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Pedr0Rocha** [mdazharuddin1011999/flutter_backdrop#4]
Hello, can you please release a new version of the package with the elevation attribute?

I'm using your package on my app, that's why I contributed, very nice package btw.

I also need the toggle button to be on the right side, maybe I can contribute to that too later.
Thanks!

**Comment by azhar1038** [comment]
Sure but I am kind of busy now. So I will try to do it as soon as possible.

**Comment by Pedr0Rocha** [comment]
Thank you sir!

**Comment by azhar1038** [comment]
No, thank you sir for your contribution. You are the first one ever contribute to any of my repository. Let this issue be open until I am not done.

**Comment by azhar1038** [comment]
I have updated the package in pub.
